name: xchango
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.6
  http: ^1.2.2

  flutter_spinkit: ^5.2.1

  loading_btn: ^1.0.3

  shared_preferences: ^2.3.2

  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/usa_flag.png
    - assets/images/thai_flag.png
    - assets/images/bg1.png
    - assets/images/bg2.png
    - assets/images/bg3.png
    - assets/images/bg4.png
    - assets/images/bg5.png
    - assets/images/bg6.png
    - assets/images/bg7.png
    - assets/images/bg8.png
    - assets/images/bg9.png
    - assets/images/bg10.png
    - assets/images/bg11.png
    - assets/images/bg12.png
    - assets/images/bg13.png
    - assets/images/bg14.png
    - assets/images/bg15.png

# Localization settings
l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
